defmodule Unex.Dev do
  @moduledoc """
  Preflight and configuration helpers for `mix unex.dev` — running a real Unex
  node on a developer's machine.

  This module deliberately contains **no second implementation** of anything the
  server already does. The dispatcher bundle is built by
  `mix unex.compile_dispatcher`; configuration is resolved by
  `config/runtime.exs` from the ordinary `UNEX_*` variables; the node itself is
  the ordinary `Unex.Application` supervision tree. What lives here is only the
  small amount of knowledge a local run needs *before* the node boots:

    * what UCM version a compiled `.uc` bundle was built by, so a mismatch is
      caught in milliseconds instead of as four ten-second accept timeouts
      inside `Unex.Dispatcher.init/1`;
    * where a dev node keeps the credentials it generated, so restarting does
      not silently orphan every AES-256-GCM-encrypted `Unex.Config` value;
    * what to print so the developer can see exactly how this node differs from
      a production one.

  See `docs/local-dev.md` for the design this supports.
  """

  @dev_env_file "dev.env"

  # Env vars a dev node persists across restarts. `UNEX_SECRET` and
  # `UNEX_CONFIG_KEY` are generated by `config/runtime.exs` when unset; keeping
  # them means an encrypted Config value written yesterday is still readable
  # today. `UNEX_DASHBOARD_SECRET` only costs open dashboard sessions, but it is
  # free to keep.
  @persisted_vars ["UNEX_SECRET", "UNEX_CONFIG_KEY", "UNEX_DASHBOARD_SECRET"]

  @doc "Environment variables a dev node carries across restarts."
  def persisted_vars, do: @persisted_vars

  @doc """
  Resolves which data directory a dev node uses: an explicit override, then
  `UNEX_DATA`, then `~/.local/share/unex/dev`.

  The default is under XDG rather than `./data` so a dev node does not scribble
  into the checkout. `mix unex.dev` and `mix unex.deploy` both call this, which
  is what lets `mix unex.deploy` find the credentials the node wrote down
  without being told where to look.
  """
  @spec data_dir(Path.t() | nil) :: Path.t()
  def data_dir(override \\ nil) do
    (present(override) || present(System.get_env("UNEX_DATA")) || default_data_dir())
    |> Path.expand()
  end

  defp default_data_dir do
    Path.join([System.user_home!(), ".local", "share", "unex", "dev"])
  end

  defp present(value) when is_binary(value) do
    case String.trim(value) do
      "" -> nil
      trimmed -> trimmed
    end
  end

  defp present(_), do: nil

  # ---------------------------------------------------------------------------
  # Dispatcher bundle version
  # ---------------------------------------------------------------------------

  @doc """
  Reads the UCM version string recorded in the header of a compiled `.uc`
  bundle.

  A bundle produced by `ucm compile` starts with a big-endian unsigned 32-bit
  length followed by that many bytes of version text:

      00000000: 0000 0023 7265 6c65 6173 652f 312e 322e  ...#release/1.2.
      00000010: 3020 2862 7569 6c74 206f 6e20 3230 3236  0 (built on 2026

  UCM refuses to run a bundle whose version differs from its own, so this is
  the cheapest way to find out ahead of boot whether the dispatcher will work.

  Returns `{:ok, "release/1.2.0 (built on 2026-04-14)"}`, `{:error, :missing}`
  when there is no such file, or `{:error, :unrecognized_format}` when the
  bytes are not a `.uc` header.
  """
  @spec bundle_version(Path.t()) :: {:ok, String.t()} | {:error, atom()}
  def bundle_version(path) do
    case File.read(path) do
      {:ok, bytes} -> parse_bundle_header(bytes)
      {:error, :enoent} -> {:error, :missing}
      {:error, reason} -> {:error, reason}
    end
  end

  # The length guard matters: without it a non-.uc file whose first four bytes
  # happen to be large would have us slice gigabytes out of a binary.
  defp parse_bundle_header(<<len::unsigned-big-integer-size(32), rest::binary>>)
       when len > 0 and len <= 128 and byte_size(rest) >= len do
    <<version::binary-size(^len), _payload::binary>> = rest

    if String.starts_with?(version, "release/") and String.printable?(version) do
      {:ok, version}
    else
      {:error, :unrecognized_format}
    end
  end

  defp parse_bundle_header(_bytes), do: {:error, :unrecognized_format}

  @doc """
  Extracts the bare release number from a UCM version string.

      iex> Unex.Dev.release_number("release/1.2.0 (built on 2026-04-14)")
      {:ok, "1.2.0"}

  `Unex.UCM.version/0` already returns the bare number for the *binary*; this
  is its counterpart for the string embedded in a bundle.
  """
  @spec release_number(String.t()) :: {:ok, String.t()} | {:error, :unrecognized_format}
  def release_number(version) when is_binary(version) do
    case Regex.run(~r/(\d+\.\d+\.\d+)/, version) do
      [_, number] -> {:ok, number}
      nil -> {:error, :unrecognized_format}
    end
  end

  @doc """
  Decides whether the dispatcher bundle at `path` can be run by a UCM whose
  release number is `ucm_release`.

  Returns `{:ok, version_string}` when the bundle matches, or
  `{:rebuild, reason}` when it is absent, unreadable, or was built by a
  different UCM. `reason` is a term suitable for `explain/1`.
  """
  @spec bundle_status(Path.t(), String.t()) :: {:ok, String.t()} | {:rebuild, term()}
  def bundle_status(path, ucm_release) when is_binary(ucm_release) do
    with {:ok, version} <- bundle_version(path),
         {:ok, number} <- release_number(version) do
      if number == ucm_release do
        {:ok, version}
      else
        {:rebuild, {:version_mismatch, number, ucm_release}}
      end
    else
      {:error, reason} -> {:rebuild, reason}
    end
  end

  @doc "Renders a `bundle_status/2` rebuild reason as a sentence for humans."
  @spec explain(term()) :: String.t()
  def explain(:missing), do: "no dispatcher bundle yet"

  def explain(:unrecognized_format),
    do: "the file is not a compiled Unison bundle"

  def explain({:version_mismatch, bundle, ucm}),
    do: "it was built by UCM #{bundle} but this machine runs UCM #{ucm}"

  def explain(other), do: "could not be read (#{inspect(other)})"

  # ---------------------------------------------------------------------------
  # Persisted dev credentials
  # ---------------------------------------------------------------------------

  @doc "Path of the credential file inside a dev data directory."
  @spec env_file(Path.t()) :: Path.t()
  def env_file(data_dir), do: Path.join(data_dir, @dev_env_file)

  @doc """
  Parses `KEY=VALUE` lines. Blank lines and `#` comments are ignored; a value
  may contain `=`. Unknown keys are kept — this is a plain env file, not a
  schema.
  """
  @spec parse_env(String.t()) :: %{optional(String.t()) => String.t()}
  def parse_env(text) when is_binary(text) do
    text
    |> String.split("\n")
    |> Enum.reduce(%{}, fn line, acc ->
      trimmed = String.trim(line)

      cond do
        trimmed == "" -> acc
        String.starts_with?(trimmed, "#") -> acc
        true -> put_pair(acc, trimmed)
      end
    end)
  end

  defp put_pair(acc, line) do
    case String.split(line, "=", parts: 2) do
      [key, value] -> Map.put(acc, String.trim(key), String.trim(value))
      _ -> acc
    end
  end

  @doc "Renders a map back to `KEY=VALUE` lines, sorted for a stable diff."
  @spec render_env(map()) :: String.t()
  def render_env(vars) when is_map(vars) do
    body =
      vars
      |> Enum.sort()
      |> Enum.map_join("\n", fn {key, value} -> "#{key}=#{value}" end)

    """
    # Generated by `mix unex.dev`. These are development credentials for this
    # data directory only. Keeping them stable is what lets encrypted
    # Unex.Config values written by an earlier run still decrypt today.
    #{body}
    """
  end

  @doc "Reads a credential file, returning an empty map when it is absent."
  @spec read_env_file(Path.t()) :: %{optional(String.t()) => String.t()}
  def read_env_file(path) do
    case File.read(path) do
      {:ok, text} -> parse_env(text)
      {:error, _} -> %{}
    end
  end

  @doc """
  Writes a credential file with owner-only permissions, creating its directory.
  """
  @spec write_env_file!(Path.t(), map()) :: :ok
  def write_env_file!(path, vars) do
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, render_env(vars))
    File.chmod!(path, 0o600)
    :ok
  end

  # ---------------------------------------------------------------------------
  # Banner
  # ---------------------------------------------------------------------------

  @doc """
  Renders the boot banner.

  The banner is the design constraint made visible: everything a local node
  does differently from a production one is named here, so "it worked in dev"
  cannot be manufactured by omission.

  Expects a map with `:api_url`, `:secret`, `:data_dir`, `:ucm_path`,
  `:ucm_version`, `:dispatcher_path`, `:dispatcher_version`, `:pool_size`,
  `:node` and `:dashboard` (either `nil` or a URL).
  """
  @spec banner(map()) :: String.t()
  def banner(%{} = info) do
    dashboard =
      case info.dashboard do
        nil -> "off (pass --dashboard to enable)"
        url -> url
      end

    """

    ================================================================
     unex dev — a real Unex node, single node, on this machine
    ================================================================
      API            #{info.api_url}
      Dashboard      #{dashboard}
      Node           #{info.node}
      Data           #{info.data_dir}
      UCM            #{info.ucm_path} (#{info.ucm_version})
      Dispatcher     #{info.dispatcher_path}
                     #{info.dispatcher_version}, pool of #{info.pool_size}

      How this differs from a production node:
        * one node, so per-node storage cannot surprise you here —
          Storage, Config, Scratch, Log and Blobs are NOT replicated
        * the dispatcher bundle is built by the UCM above; a server
          running a different UCM cannot run this bundle, and vice versa
        * the pool is smaller, so concurrency behaves differently

      Point a Unison program at this node:

        export UNEX_URL=#{info.api_url}
        export UNEX_SECRET=#{info.secret}

      Check it:

        curl -s #{info.api_url}/health
        curl -s -H "Authorization: Bearer $UNEX_SECRET" #{info.api_url}/services

      Ctrl-C twice to stop.
    ================================================================
    """
  end
end
